# -*- coding: utf-8 -*-
"""intent_arabic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vvAUz11DWgqShNI23ImdsOulypYEtCdY
"""

from google.colab import drive
drive.mount('/content/drive')

from google.colab import files
uploaded = files.upload()

# =========================================
# 1) Install
# =========================================
!pip -q install transformers datasets accelerate pandas scikit-learn matplotlib joblib

# =========================================
# 2) Imports
# =========================================
import os
import re
import json
import joblib
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

from datasets import load_dataset
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
    classification_report
)

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    DataCollatorWithPadding,
    TrainingArguments,
    Trainer,
    pipeline,
)

# =========================================
# 3) File paths
# =========================================
train_csv = "arabic_clean_intent.csv"
response_csv = "intent_response_map_ar.csv"
followup_csv = "intent_follow_up_map_ar.csv"

# =========================================
# 4) Load files
# =========================================
train_df = pd.read_csv(train_csv)
response_df = pd.read_csv(response_csv)
followup_df = pd.read_csv(followup_csv)

print("Train columns:", train_df.columns.tolist())
print("Response columns:", response_df.columns.tolist())
print("Follow-up columns:", followup_df.columns.tolist())

# =========================================
# 5) Basic checks
# =========================================
required_cols = {"text", "intent"}
if not required_cols.issubset(train_df.columns):
    raise ValueError(f"Train file must contain columns: {required_cols}")

if not {"intent", "response"}.issubset(response_df.columns):
    raise ValueError("intent_response_map_ar.csv must contain columns: intent,response")

if not {"intent", "follow_up"}.issubset(followup_df.columns):
    raise ValueError("intent_follow_up_map_ar.csv must contain columns: intent,follow_up")

# =========================================
# 6) Normalize helpers
# =========================================
def normalize_text(text):
    text = str(text).strip().lower()
    text = re.sub(r"ـ+", "", text)
    text = re.sub(r"[أإآٱ]", "ا", text)
    text = re.sub(r"ى", "ي", text)
    text = re.sub(r"ؤ", "و", text)
    text = re.sub(r"ئ", "ي", text)
    text = re.sub(r"ة", "ه", text)
    text = re.sub(r"[\u0617-\u061A\u064B-\u0652]", "", text)
    text = re.sub(r"[^\u0600-\u06FFa-zA-Z0-9\s_]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

def normalize_intent(intent):
    return str(intent).strip().lower()

# =========================================
# 7) Clean train data
# =========================================
train_df = train_df.dropna(subset=["text", "intent"]).copy()
train_df["text"] = train_df["text"].astype(str).apply(normalize_text)
train_df["intent"] = train_df["intent"].astype(str).apply(normalize_intent)

train_df = train_df[train_df["text"].str.strip() != ""].copy()
train_df = train_df.drop_duplicates(subset=["text", "intent"]).reset_index(drop=True)

print("\nAfter cleaning:", train_df.shape)
print(train_df["intent"].value_counts())

# استخدم فقط الـ intents الموجودة فعلًا في الداتا
allowed_intents = sorted(train_df["intent"].unique().tolist())

print("\nAllowed intents:")
print(allowed_intents)

if len(train_df) == 0:
    raise ValueError("train_df is empty after cleaning.")

# =========================================
# 8) Split train / validation
# =========================================
train_df, val_df = train_test_split(
    train_df,
    test_size=0.2,
    random_state=42,
    stratify=train_df["intent"]
)

train_df = train_df.reset_index(drop=True)
val_df = val_df.reset_index(drop=True)

print("\nBefore upsampling:")
print(train_df["intent"].value_counts())

# =========================================
# 8.1) Upsample rare classes in TRAIN only
# =========================================
min_samples_per_class = 700

parts = []
for intent_name, group in train_df.groupby("intent"):
    if len(group) < min_samples_per_class:
        extra = group.sample(
            n=min_samples_per_class - len(group),
            replace=True,
            random_state=42
        )
        group = pd.concat([group, extra], ignore_index=True)
    parts.append(group)

train_df = pd.concat(parts, ignore_index=True)
train_df = train_df.sample(frac=1, random_state=42).reset_index(drop=True)

print("\nAfter upsampling:")
print(train_df["intent"].value_counts())

print("\nTrain size:", len(train_df))
print("Validation size:", len(val_df))

# =========================================
# 9) Save cleaned splits
# =========================================
train_split_csv = "intent_train_split_13_balanced.csv"
val_split_csv = "intent_val_split_13_balanced.csv"

train_df.to_csv(train_split_csv, index=False, encoding="utf-8-sig")
val_df.to_csv(val_split_csv, index=False, encoding="utf-8-sig")

# =========================================
# 10) Label mappings
# =========================================
label2id = {label: idx for idx, label in enumerate(allowed_intents)}
id2label = {idx: label for label, idx in label2id.items()}

print("\nlabel2id:")
print(label2id)

from sklearn.utils.class_weight import compute_class_weight

train_labels_for_weights = train_df["intent"].map(label2id).values

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.array(sorted(label2id.values())),
    y=train_labels_for_weights
)

class_weights = torch.tensor(class_weights, dtype=torch.float)
print("Class weights:", class_weights)
# =========================================
# 11) Load dataset
# =========================================
dataset = load_dataset(
    "csv",
    data_files={
        "train": train_split_csv,
        "validation": val_split_csv
    }
)

def add_labels(example):
    example["label"] = label2id[normalize_intent(example["intent"])]
    return example

dataset = dataset.map(add_labels)

# =========================================
# 12) Tokenizer
# =========================================
model_checkpoint = "FacebookAI/xlm-roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        truncation=True,
        max_length=128
    )

tokenized_dataset = dataset.map(tokenize_function, batched=True)

keep_cols = {"input_ids", "attention_mask", "label"}

tokenized_dataset["train"] = tokenized_dataset["train"].remove_columns(
    [c for c in tokenized_dataset["train"].column_names if c not in keep_cols]
)
tokenized_dataset["validation"] = tokenized_dataset["validation"].remove_columns(
    [c for c in tokenized_dataset["validation"].column_names if c not in keep_cols]
)

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

# =========================================
# 13) Load model
# =========================================
model = AutoModelForSequenceClassification.from_pretrained(
    model_checkpoint,
    num_labels=len(allowed_intents),
    id2label=id2label,
    label2id=label2id,
)

# =========================================
# 14) Freeze all first
# =========================================
for param in model.parameters():
    param.requires_grad = False

# =========================================
# 14.1) Unfreeze last 2 transformer layers + classifier
# XLM-R has encoder.layer[0..11]
# =========================================
for name, param in model.named_parameters():
    if (
        "encoder.layer.10." in name or
        "encoder.layer.11." in name or
        "classifier" in name
    ):
        param.requires_grad = True

print("\nTrainable parameters only:")
for name, param in model.named_parameters():
    if param.requires_grad:
        print(name)

total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"\nTotal params     : {total_params:,}")
print(f"Trainable params : {trainable_params:,}")
print(f"Trainable %      : {100 * trainable_params / total_params:.4f}%")

# =========================================
# 15) Metrics
# =========================================
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)

    acc = accuracy_score(labels, preds)
    f1_weighted = f1_score(labels, preds, average="weighted", zero_division=0)
    f1_macro = f1_score(labels, preds, average="macro", zero_division=0)

    return {
        "accuracy": acc,
        "f1_weighted": f1_weighted,
        "f1_macro": f1_macro
    }

# =========================================
# 16) Training arguments
# =========================================
training_args = TrainingArguments(
    output_dir="./xlmr_intent_13_results",
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=6,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="f1_weighted",
    greater_is_better=True,
    save_total_limit=2,
    report_to="none",
    fp16=torch.cuda.is_available(),
)

# =========================================
# 17) Trainer
# =========================================
from transformers import Trainer
import torch.nn as nn

class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        labels = inputs.get("labels")
        outputs = model(
            input_ids=inputs["input_ids"],
            attention_mask=inputs["attention_mask"]
        )
        logits = outputs.get("logits")

        loss_fct = nn.CrossEntropyLoss(weight=class_weights.to(logits.device))
        loss = loss_fct(logits.view(-1, model.config.num_labels), labels.view(-1))

        return (loss, outputs) if return_outputs else loss

trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"],
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

# =========================================
# 18) Train
# =========================================
trainer.train()

# =========================================
# 19) Evaluate
# =========================================
eval_results = trainer.evaluate()
print("\nEvaluation results:")
print(eval_results)

# =========================================
# 20) Predictions on validation
# =========================================
pred_output = trainer.predict(tokenized_dataset["validation"])
y_true = pred_output.label_ids
y_pred = np.argmax(pred_output.predictions, axis=1)

print("\nValidation Accuracy:", accuracy_score(y_true, y_pred))
print("Validation F1 Weighted:", f1_score(y_true, y_pred, average="weighted", zero_division=0))
print("Validation F1 Macro:", f1_score(y_true, y_pred, average="macro", zero_division=0))

print("\nClassification Report:\n")
print(classification_report(
    y_true,
    y_pred,
    labels=sorted(id2label.keys()),
    target_names=[id2label[i] for i in sorted(id2label.keys())],
    digits=4,
    zero_division=0
))

labels_sorted = sorted(id2label.keys())
display_labels = [id2label[i] for i in labels_sorted]

cm = confusion_matrix(y_true, y_pred, labels=labels_sorted)

plt.figure(figsize=(14, 12))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=display_labels)
disp.plot(cmap="Blues", xticks_rotation=45)
plt.title("Confusion Matrix - 13 Intent Model")
plt.show()

# =========================================
# 21) Save model
# =========================================
save_dir = "./xlmr_intent_model_13_balanced"
trainer.save_model(save_dir)
tokenizer.save_pretrained(save_dir)

with open(os.path.join(save_dir, "label2id.json"), "w", encoding="utf-8") as f:
    json.dump(label2id, f, ensure_ascii=False, indent=2)

with open(os.path.join(save_dir, "id2label.json"), "w", encoding="utf-8") as f:
    json.dump({str(k): v for k, v in id2label.items()}, f, ensure_ascii=False, indent=2)

print(f"\nModel saved to: {save_dir}")


# =========================================
# 22) Clean response / follow-up maps
# =========================================
response_df["intent"] = response_df["intent"].astype(str).apply(normalize_intent)
followup_df["intent"] = followup_df["intent"].astype(str).apply(normalize_intent)

response_df["response"] = response_df["response"].astype(str).fillna("")
followup_df["follow_up"] = followup_df["follow_up"].astype(str).fillna("")

response_map = dict(zip(response_df["intent"], response_df["response"]))
followup_map = dict(zip(followup_df["intent"], followup_df["follow_up"]))

# =========================================
# 23) Manual Arabic overrides
# =========================================
manual_response_ar = {
    "check_data_usage": "بدك تعرف كم ضايل عندك نت؟ 👀 فيك تشوفه من التطبيق بكل سهولة",
    "renew_package": "بدك تشحن؟ ولا أسهل 😎 بتقدر تعملها من التطبيق أو بطاقة شحن",
    "payment_issue": "شكل العملية ما زبطت معك 😕 تأكد من بيانات الدفع وجرب مرة ثانية",
    "balance_transfer": "بدك تحولي رصيد؟ تمام 👌 فيك تعملها من خدمة تحويل الرصيد",
    "offer_inquiry": "بدك تشوف العروض؟ 🔥 في كذا عرض حلو، خبرني شو بدك بالزبط",
    "slow_internet": "شكله النت عندك شوي تعبان 😅 جرب تعمل إعادة تشغيل للجهاز وخبرني شو بصير",
    "no_signal": "واضح الشبكة مش راضية تزبط 😅 جرب تطفي الجهاز وتشغله",
    "technical_support": "تمام خلينا نحلها سوا 💪 احكيلي شو المشكلة بالزبط",
    "network_status": "بدك تعرف وضع الشبكة؟ 👀 فيك تشوفه من التطبيق",
    "network_complaint": "تمام، فينا نسجل شكوى ونحل المشكلة مع بعض 👍",
    "greeting": "هلا وغلا 👋 كيف فيني أساعدك؟",
    "goodbye": "يعطيك العافية 🤍 وإذا احتجت شي أنا موجودد",
    "other": "مش واضح عليّ شو قصدك 😅 ممكن توضحلي أكثر؟",
    "feedback": "ولا يهمك 🤍 يسعدني تعليقك، وإذا عندك أي ملاحظة ثانية احكيلي",
}

manual_followup_ar = {
    "check_data_usage": "بدك أشرح لك كيف توصل للتفاصيل؟",
    "renew_package": "بدك خطوات الشحن بالتفصيل؟",
    "payment_issue": "بدك أساعدك نحل المشكلة خطوة خطوة؟",
    "balance_transfer": "بدك خطوات التحويل؟",
    "offer_inquiry": "بدك أشرح لك العروض المتاحة؟",
    "slow_internet": "بدك خطوات نحل المشكلة مع بعض؟",
    "no_signal": "بدك نجرب حلول ثانية؟",
    "technical_support": "احكيلي شو صاير معك بالزبط 👀",
    "network_status": "بدك أتحقق لك من الشبكة؟",
    "network_complaint": "بدك نكمل تسجيل الشكوى؟",
    "greeting": "شو حاب تعرف؟ 😄",
    "goodbye": "في شي ثاني قبل ما تروح؟ 👀",
    "other": "ممكن توضح أكثر؟",
    "feedback": "في شي ثاني أقدر أساعدك فيه؟",
}

# نخلي manual overrides أعلى أولوية من CSV
response_map.update(manual_response_ar)
followup_map.update(manual_followup_ar)

# fallback أخير لو intent جديد أو ناقص
default_response_map = {
    "greeting": "هلا وغلا، كيف فيني أساعدك؟",
    "goodbye": "مع السلامة، وإذا احتجت أي شي أنا موجودة.",
    "feedback": "شكراً إلك على ملاحظتك، وإذا بدك أي مساعدة أنا جاهزة.",
    "slow_internet": "واضح إن سرعة الإنترنت عندك فيها مشكلة. خلينا نجرب خطوات بسيطة للحل.",
    "no_signal": "واضح إن في مشكلة بالإشارة. خليني أساعدك بخطوات سريعة.",
    "payment_issue": "واضح إن عندك مشكلة بالدفع أو الفاتورة. خلينا نحلها مع بعض.",
    "check_data_usage": "تقدري تعرفي استهلاكك الحالي من خلال التطبيق أو بخطوات بسيطة.",
    "renew_package": "تقدري تجددي الباقة بسهولة. إذا بدك أشرح لك الخطوات.",
    "network_complaint": "تقدري تقدمي شكوى بخصوص الشبكة، وأنا أساعدك بالخطوات.",
    "technical_support": "أكيد، أنا جاهزة أساعدك بالدعم الفني خطوة بخطوة.",
    "network_status": "أقدر أساعدك تعرفي حالة الشبكة الحالية.",
    "offer_inquiry": "أقدر أوضح لك العروض والباقات المتاحة.",
    "balance_transfer": "تقدري تعملي تحويل رصيد، وإذا بدك أشرح لك الطريقة.",
    "other": "ممكن توضحي طلبك أكثر حتى أقدر أساعدك بشكل أدق؟"
}

default_followup_map = {
    "greeting": "شو حابة أعرفك أو أساعدك فيه؟",
    "goodbye": "في شي ثاني قبل ما تروحي؟",
    "feedback": "هل عندك أي ملاحظة إضافية؟",
    "slow_internet": "بدك أجرب معك خطوات تحسين السرعة؟",
    "no_signal": "بدك نجرب خطوات حل مشكلة الإشارة؟",
    "payment_issue": "بدك أشرح لك خطوات حل مشكلة الدفع؟",
    "check_data_usage": "بدك أشرح لك كيف تشوفي الاستهلاك؟",
    "renew_package": "بدك خطوات تجديد الباقة؟",
    "network_complaint": "بدك نكمل بخطوات تقديم الشكوى؟",
    "technical_support": "احكيلي شو المشكلة التقنية بالضبط.",
    "network_status": "بدك أساعدك تعرفي وضع الشبكة الآن؟",
    "offer_inquiry": "بدك أشرح لك أفضل عرض أو باقة مناسبة؟",
    "balance_transfer": "بدك خطوات تحويل الرصيد؟",
    "other": "ممكن تشرحيلي طلبك بطريقة أوضح؟"
}

for intent in allowed_intents:
    if intent not in response_map or str(response_map[intent]).strip() == "":
        response_map[intent] = default_response_map.get(intent, "ما عندي رد لهذا الانتنت")
    if intent not in followup_map or str(followup_map[intent]).strip() == "":
        followup_map[intent] = default_followup_map.get(intent, "كيف أقدر أساعدك أكثر؟")

joblib.dump(response_map, os.path.join(save_dir, "response_map_ar.joblib"))
joblib.dump(followup_map, os.path.join(save_dir, "followup_map_ar.joblib"))

print("\nFinal response_map keys:", sorted(response_map.keys()))
print("Final followup_map keys:", sorted(followup_map.keys()))
print("Arabic response/follow-up maps saved successfully.")

# =========================
# =========================================
# 24) Rule-based override (fixed)
# =========================================
def rule_based_override(text):
    t = normalize_text(text)

    greetings = {
        "مرحبا", "مرحباا", "هلا", "هلااا", "هلا والله", "هلا فيك",
        "ياهلا", "يا هلا وغلا", "اهلا", "اهلين", "اهلين فيك",
        "حي الله", "حي الله فيك", "السلام عليكم", "يسعد صباحك",
        "يسعد مساك", "كيفك", "كيف الحال", "شو الاخبار",
        "hello", "hi", "hey", "قوك", "شلونك"
    }

    goodbyes = {
        "مع السلامه", "مع السلامة", "باي", "bye", "goodbye", "يلا باي", "سلام"
    }

    feedback_words = {
        "شكرا", "شكراً", "شكرا الك", "مشكور", "يسلمو", "يسلم ايديك",
        "يعطيك العافيه", "الله يعطيك العافيه", "تمام شكرا",
        "شكرا كثير", "شكرن", "اشكرك", "thank you", "thanks",
        "thanks a lot", "appreciate it", "great thanks", "يعطيك العافية",
        "يسلمو كتير", "مشكور كتير", "كفو", "ما قصرت", "يسلم هالايدين",
        "يسلمو ايديك", "يسلم هالراس", "كفو عليك", "الله يسعدك",
        "ما قصرت والله", "مشكور يا غالي", "ثانكس", "ثانكيو"
    }

    if t in greetings:
        return "greeting"

    if t in goodbyes:
        return "goodbye"

    if t in feedback_words:
        return "feedback"

    # check_data_usage قوي
    if re.search(r"(قديش|كم|احكيلي|اعرف|اشوف|شيك|اتأكد|تاكد).*(ضايل|باقي|متبقي|استهلاك|صرف|نت|بيانات|باقه|باقة)", t):
        return "check_data_usage"

    if re.search(r"(ضايل|باقي|متبقي|استهلاك|استهلاكي|صرفت|صرفي|خلصت الباقه|خلصت الباقة|لسا في نت|في نت)", t):
        return "check_data_usage"

    # slow_internet قوي
    if re.search(r"(النت|الانترنت|التصفح|الصفحات).*(بطي|تعبان|بخزي|بعلق|بتعلق|هنق|يهنق|خف|مش طبيعي|مش ثابت|غير مستقر|ياخد وقت)", t):
        return "slow_internet"

    if re.search(r"(بطي|تعبان|بخزي|بعلق|بتعلق|هنق|يهنق|التصفح بطي|الصفحات بتعلق)", t):
        return "slow_internet"

    # network_status قوي
    if re.search(r"(حاله|حالة|وضع|شو وضع|افحص|تفحص|تحقق).*(الشبكه|الشبكة|النت|الخدمه|الخدمة)", t):
        return "network_status"

    if re.search(r"(هل في عطل|في عطل|الشبكه شغاله|الشبكة شغالة|الخدمه شغاله|الخدمة شغالة)", t):
        return "network_status"

    # no_signal قوي
    if re.search(r"(ما في|مافي|لا يوجد|معدومه|معدومة|خارج الخدمه|خارج الخدمة).*(اشاره|إشارة|شبكه|شبكة|تغطيه|تغطية)", t):
        return "no_signal"

    # payment_issue قوي
    if re.search(r"(دفعت|دفع|شحن|شحنت|خصم|انخصم|الرصيد|فاتوره|فاتورة).*(ما صار|ما وصل|فشل|مشكله|مشكلة|اختفى|اختفي|ما زبط)", t):
        return "payment_issue"

    # technical_support قوي
    if re.search(r"(دعم|تقني|فني|مساعده|مساعدة|اصلح|أصلح|حل).*(مشكله|مشكلة|خطوه|خطوة|فورا|الان)", t):
        return "technical_support"

    return None
# =========================================
# 24) Load model for inference
# =========================================
device = 0 if torch.cuda.is_available() else -1

clf = pipeline(
    "text-classification",
    model=save_dir,
    tokenizer=save_dir,
    device=device
)

# =========================================
# 25) Conversation state
# =========================================
conversation_state = {
    "last_intent": None,
    "awaiting_followup": False
}

# =========================================
# 26) Arabic chatbot predict
# =========================================
def chatbot_predict_ar(text):
    global conversation_state

    clean_text = normalize_text(text)

    # ========================
    # Follow-up handling
    # ========================
    if conversation_state["awaiting_followup"]:
        yes_words = {"نعم", "اه", "ايوه", "أكيد", "اكيد"}
        no_words = {"لا", "مو", "مش"}

        if clean_text in yes_words:
            conversation_state["awaiting_followup"] = False
            return {
                "text": text,
                "intent": "follow_up_response",
                "confidence": 1.0,
                "response": "تمام خلينا نكمل خطوة خطوة",
                "follow_up": None
            }

        elif clean_text in no_words:
            conversation_state["awaiting_followup"] = False
            return {
                "text": text,
                "intent": "follow_up_response",
                "confidence": 1.0,
                "response": "تمام، إذا احتجت أي شي بعدين أنا موجودة",
                "follow_up": None
            }

    # ========================
    # Rule-based override
    # ========================
    forced_intent = rule_based_override(text)

    if forced_intent is not None:
        predicted_intent = forced_intent
        confidence = 0.99

    else:
        pred = clf(clean_text, truncation=True)[0]
        predicted_intent = normalize_intent(pred["label"])
        confidence = float(pred["score"])

        # ========================
        # 🔥 BOOST (تحسين ذكي)
        # ========================
        if predicted_intent == "check_data_usage" and confidence < 0.60:
            confidence += 0.20

        elif predicted_intent == "network_status" and confidence < 0.60:
            confidence += 0.15

        elif predicted_intent == "slow_internet" and confidence < 0.60:
            confidence += 0.10

        # ========================
        # Threshold
        # ========================
        if confidence < 0.40:
            predicted_intent = "other"

    # ========================
    # Response
    # ========================
    response = response_map.get(predicted_intent, default_response_map.get(predicted_intent))
    follow_up = followup_map.get(predicted_intent, default_followup_map.get(predicted_intent))

    conversation_state["last_intent"] = predicted_intent
    conversation_state["awaiting_followup"] = True if follow_up and str(follow_up).strip() else False

    return {
        "text": text,
        "intent": predicted_intent,
        "confidence": confidence,
        "response": response,
        "follow_up": follow_up
    }
# =========================================
# 27) Quick tests
# =========================================
tests = [
    "مرحبا",
    "كيفك",
    "النت بطيء",
    "ما في شبكة",
    "الدفع فشل",
    "بدي عرض مناسب",
    "كم ضايل عندي نت",
    "شكرا",
    "مع السلامه"
]

print("\nQuick Tests:\n")
for t in tests:
    result = chatbot_predict_ar(t)
    print("Input:", t)
    print("Intent:", result["intent"])
    print("Response:", result["response"])
    print("Follow-up:", result["follow_up"])
    print("-" * 50)

# =========================================
# 28) Interactive Arabic mode
# =========================================
while True:
    text = input("أدخل النص: ").strip()
    clean_text = text.lower().strip()

    if clean_text in ["exit", "quit", "خروج", "انهاء", "وقف", "باي"]:
        print("\nBot:")
        print("مع السلامة! نتمنى لك يوم سعيد")
        break

    result = chatbot_predict_ar(text)

    print("\nBot Response:")
    print("Response:", result["response"])
    print("Follow-up:", result["follow_up"])

    print("\nAnalysis:")
    print("Intent:", result["intent"])
    print("Confidence:", result["confidence"])

    print("=" * 50)

import shutil
import os

source = "./xlmr_intent_model_13_balanced"
destination = "/content/drive/MyDrive/CoCare/Intent_Ara/xlmr_intent_model_13_balanced"

if os.path.exists(destination):
    shutil.rmtree(destination)

shutil.copytree(source, destination)

print("Model copied to Drive:")
print(destination)

# توحيد أسماء التصنيفات بين التدريب والتست
test_df["intent"] = test_df["intent"].astype(str).str.strip().str.lower()

test_df["intent"] = test_df["intent"].replace({
    "thanks": "feedback"
})

# تأكدي من التوزيع بعد التعديل
print(test_df["intent"].value_counts())

from google.colab import files
uploaded = files.upload()

from sklearn.metrics import accuracy_score, f1_score, classification_report

# =========================
# Wider merge to reach ~85
# =========================

MERGE_MAP = {
    # مشاكل الشبكة
    "slow_internet": "network_issue",
    "network_complaint": "network_issue",
    "network_status": "network_issue",
    "no_signal": "network_issue",
    "technical_support": "network_issue",

    # الحساب/الباقة/الدفع
    "payment_issue": "account_package",
    "renew_package": "account_package",
    "check_data_usage": "account_package",
    "balance_transfer": "account_package",

    # العروض
    "offer_inquiry": "offer_inquiry",

    # محادثات عامة
    "greeting": "general_chat",
    "goodbye": "general_chat",
    "thanks": "general_chat",
    "feedback": "general_chat",

    # غير واضح
    "other": "other",
}


def merge_intent(intent):
    intent = str(intent).strip().lower()
    return MERGE_MAP.get(intent, intent)


test_df["intent_merged_v2"] = test_df["intent"].apply(merge_intent)
test_df["pred_merged_v2"] = test_df["pred"].apply(merge_intent)

acc = accuracy_score(test_df["intent_merged_v2"], test_df["pred_merged_v2"])
f1_w = f1_score(test_df["intent_merged_v2"], test_df["pred_merged_v2"], average="weighted", zero_division=0)
f1_m = f1_score(test_df["intent_merged_v2"], test_df["pred_merged_v2"], average="macro", zero_division=0)

print("Merged V2 Accuracy:", acc)
print("Merged V2 F1 Weighted:", f1_w)
print("Merged V2 F1 Macro:", f1_m)

print("\nMerged V2 Report:")
print(classification_report(
    test_df["intent_merged_v2"],
    test_df["pred_merged_v2"],
    digits=4,
    zero_division=0
))

test_df.to_csv("intent_test_clean_aligned_colloquial_augmented.csv", index=False, encoding="utf-8-sig")

errors_v2 = test_df[test_df["intent_merged_v2"] != test_df["pred_merged_v2"]]
errors_v2.to_csv("intent_test_merged_v2_errors.csv", index=False, encoding="utf-8-sig")

print("\nTop remaining errors:")
print(
    errors_v2.groupby(["intent_merged_v2", "pred_merged_v2"])
    .size()
    .reset_index(name="count")
    .sort_values("count", ascending=False)
    .head(20)
)

print(
    errors[["text", "intent", "final_pred", "score"]]
    .head(30)
    .to_string(index=False)
)

errors_df = test_df[test_df["intent"] != test_df["pred"]].copy()

print("Wrong predictions:", len(errors_df))

print(errors_df[["text", "intent", "pred", "score"]].head(50).to_string())

print(
    errors_df.groupby(["intent", "pred"])
    .size()
    .sort_values(ascending=False)
    .head(30)
)
